version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sonaerp-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sonaerp
      POSTGRES_PASSWORD: sonaerp_dev
      POSTGRES_DB: sonaerp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
