export enum Language {
  AR = 'AR',
  FR = 'FR',
  EN = 'EN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  NEEDS_IDENTIFICATION = 'NEEDS_IDENTIFICATION',
  DTAO_PREPARATION = 'DTAO_PREPARATION',
  DTAO_REVIEW = 'DTAO_REVIEW',
  PUBLISHED = 'PUBLISHED',
  BID_RECEPTION = 'BID_RECEPTION',
  BID_OPENING = 'BID_OPENING',
  TECHNICAL_EVALUATION = 'TECHNICAL_EVALUATION',
  COMMERCIAL_EVALUATION = 'COMMERCIAL_EVALUATION',
  ADJUDICATION = 'ADJUDICATION',
  CONTRACT_DRAFTING = 'CONTRACT_DRAFTING',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  IN_EXECUTION = 'IN_EXECUTION',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  DECLARED_INFRUCTUEUX = 'DECLARED_INFRUCTUEUX',
}

export enum ProcurementMode {
  APPEL_OFFRES_OUVERT = 'APPEL_OFFRES_OUVERT',
  APPEL_OFFRES_RESTREINT = 'APPEL_OFFRES_RESTREINT',
  CONSULTATION_DIRECTE = 'CONSULTATION_DIRECTE',
  GRE_A_GRE_SIMPLE = 'GRE_A_GRE_SIMPLE',
  GRE_A_GRE_APRES_CONSULT = 'GRE_A_GRE_APRES_CONSULT',
  COMMANDE_SANS_CONSULT = 'COMMANDE_SANS_CONSULT',
}

export enum BidEnvelopeType {
  TECHNICAL = 'TECHNICAL',
  COMMERCIAL = 'COMMERCIAL',
}

export enum BidStatus {
  RECEIVED = 'RECEIVED',
  OPENED = 'OPENED',
  UNDER_EVALUATION = 'UNDER_EVALUATION',
  TECHNICALLY_COMPLIANT = 'TECHNICALLY_COMPLIANT',
  TECHNICALLY_NON_COMPLIANT = 'TECHNICALLY_NON_COMPLIANT',
  COMMERCIALLY_EVALUATED = 'COMMERCIALLY_EVALUATED',
  AWARDED = 'AWARDED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum DTAOStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  AMENDED = 'AMENDED',
  CANCELLED = 'CANCELLED',
}

export enum ContractStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_VISA_LEGAL = 'PENDING_VISA_LEGAL',
  PENDING_VISA_FINANCIAL = 'PENDING_VISA_FINANCIAL',
  PENDING_APPROVAL_DG = 'PENDING_APPROVAL_DG',
  APPROVED = 'APPROVED',
  SIGNED = 'SIGNED',
  IN_EXECUTION = 'IN_EXECUTION',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
  COMPLETED = 'COMPLETED',
  RESILIE = 'RESILIE',
}

export enum AvenantStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_CCC_APPROVAL = 'PENDING_CCC_APPROVAL',
  PENDING_LEGAL_VISA = 'PENDING_LEGAL_VISA',
  PENDING_FINANCIAL_VISA = 'PENDING_FINANCIAL_VISA',
  APPROVED = 'APPROVED',
  SIGNED = 'SIGNED',
  REJECTED = 'REJECTED',
}

export enum AvenantType {
  MODIFICATION_SCOPE = 'MODIFICATION_SCOPE',
  EXTENSION_DELAY = 'EXTENSION_DELAY',
  PRICE_REVISION = 'PRICE_REVISION',
  ADDITIONAL_WORKS = 'ADDITIONAL_WORKS',
  REDUCTION = 'REDUCTION',
}

export enum AuditAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  FAILED_LOGIN = 'FAILED_LOGIN',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  DOCUMENT_DOWNLOAD = 'DOCUMENT_DOWNLOAD',
  BID_OPEN = 'BID_OPEN',
  VOTE_CAST = 'VOTE_CAST',
  CONTRACT_SIGN = 'CONTRACT_SIGN',
  AVENANT_APPROVE = 'AVENANT_APPROVE',
  THRESHOLD_EXCEEDED = 'THRESHOLD_EXCEEDED',
  EXPORT_PDF = 'EXPORT_PDF',
}

export enum RoleCode {
  SYS_ADMIN = 'SYS_ADMIN',
  INITIATOR = 'INITIATOR',
  PROC_OFFICER = 'PROC_OFFICER',
  LEGAL_ADVISOR = 'LEGAL_ADVISOR',
  CCC_PRESIDENT = 'CCC_PRESIDENT',
  CCC_MEMBER = 'CCC_MEMBER',
  CCC_RAPPORTEUR = 'CCC_RAPPORTEUR',
  FINANCE_CONTROLLER = 'FINANCE_CONTROLLER',
  STRUCTURE_MANAGER = 'STRUCTURE_MANAGER',
  DG_APPROVER = 'DG_APPROVER',
  AUDITOR = 'AUDITOR',
}
